agent:
  # name: ""
  neoloadWebApiUrl: "https://neoload-api.saas.neotys.com"
  isOpenShiftCluster: false
  # WARNING: Do NOT hard-code or commit the NeoLoad Web API token in this file.
  # Instead, pass it at install/upgrade time with commandline argument `--set agent.neoloadWebApiToken=TOKEN`

#Proxy configuration
#proxy:
#  enabled: true
#  host: "proxy.example.com"
#  port: "8080"
#  user:
#    secretName: "my-proxy-secret"
#    secretKey: "username"
#  password:
#    secretName: "my-proxy-secret"
#    secretKey: "password"

# Private registry configuration
#registryKey:
#  enabled: true
#  registry: docker.io
#  username: userName
#  password: password
