agent:
  # name: ""
  neoloadWebApiUrl: "https://neoload-api.saas.neotys.com"
  neoloadWebApiToken: "YOUR_NEOLOAD_WEB_LONG_TERM_TOKEN"
  isOpenShiftCluster: false

# proxy configuration:
#   enabled: true
#   url: "proxy.example.com"
#   port: "8080"
#   user:
#     secretName: "my-proxy-secret"
#     secretKey: "username"
#   password:
#     secretName: "my-proxy-secret"
#     secretKey: "password"